#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

FILES=$(find src/components src/App.tsx -name "*.tsx" -o -name "*.ts" 2>/dev/null | tr '\n' ' ')

apply() { sed -i "$1" $FILES; }

# ── BLUE → accent ──────────────────────────────────────────────────
apply 's/\bbg-blue-950\b/bg-accent-subtle/g'
apply 's/\bbg-blue-900\b/bg-accent-subtle/g'
apply 's/\bbg-blue-100\b/bg-accent-subtle/g'
apply 's/\bbg-blue-50\b/bg-accent-subtle/g'
apply 's/\bbg-blue-[0-9][0-9][0-9]\b/bg-accent/g'
apply 's/\btext-blue-800\b/text-accent/g'
apply 's/\btext-blue-900\b/text-accent/g'
apply 's/\btext-blue-[0-9][0-9][0-9]\b/text-accent/g'
apply 's/\bborder-blue-[0-9][0-9][0-9]\b/border-accent/g'
apply 's/\bring-blue-[0-9][0-9][0-9]\b/ring-accent/g'
apply 's/focus:ring-blue-[0-9][0-9][0-9]\b/focus:ring-accent/g'
apply 's/hover:text-blue-[0-9][0-9][0-9]\b/hover:text-accent/g'
apply 's/hover:bg-blue-[0-9][0-9][0-9]\b/hover:bg-accent/g'
apply 's/dark:text-blue-[0-9][0-9][0-9]\b/dark:text-accent/g'
apply 's/dark:bg-blue-[0-9][0-9][0-9]\b/dark:bg-accent/g'
apply 's/dark:border-blue-[0-9][0-9][0-9]\b/dark:border-accent/g'
apply 's/dark:ring-blue-[0-9][0-9][0-9]\b/dark:ring-accent/g'
apply 's/dark:focus:ring-blue-[0-9][0-9][0-9]\b/dark:focus:ring-accent/g'
apply 's/dark:hover:text-blue-[0-9][0-9][0-9]\b/dark:hover:text-accent/g'
apply 's/dark:hover:bg-blue-[0-9][0-9][0-9]\b/dark:hover:bg-accent/g'

# ── RED + ROSE → negative ─────────────────────────────────────────
apply 's/\bbg-red-950\b/bg-negative\/10/g'
apply 's/\bbg-red-900\b/bg-negative\/10/g'
apply 's/\bbg-red-100\b/bg-negative\/10/g'
apply 's/\bbg-red-50\b/bg-negative\/10/g'
apply 's/\bbg-red-[0-9][0-9][0-9]\b/bg-negative/g'
apply 's/\btext-red-[0-9][0-9][0-9]\b/text-negative/g'
apply 's/\bborder-red-[0-9][0-9][0-9]\b/border-negative/g'
apply 's/\bring-red-[0-9][0-9][0-9]\b/ring-negative/g'
apply 's/hover:bg-red-[0-9][0-9][0-9]\b/hover:bg-negative/g'
apply 's/hover:text-red-[0-9][0-9][0-9]\b/hover:text-negative/g'
apply 's/dark:text-red-[0-9][0-9][0-9]\b/dark:text-negative/g'
apply 's/dark:bg-red-[0-9][0-9][0-9]\b/dark:bg-negative/g'
apply 's/dark:border-red-[0-9][0-9][0-9]\b/dark:border-negative/g'
apply 's/\bbg-rose-[0-9][0-9][0-9]\b/bg-negative/g'
apply 's/\btext-rose-[0-9][0-9][0-9]\b/text-negative/g'
apply 's/dark:text-rose-[0-9][0-9][0-9]\b/dark:text-negative/g'
apply 's/dark:bg-rose-[0-9][0-9][0-9]\b/dark:bg-negative/g'

# ── GREEN + EMERALD → positive ────────────────────────────────────
apply 's/\bbg-green-[0-9][0-9][0-9]\b/bg-positive/g'
apply 's/\btext-green-[0-9][0-9][0-9]\b/text-positive/g'
apply 's/\bborder-green-[0-9][0-9][0-9]\b/border-positive/g'
apply 's/hover:bg-green-[0-9][0-9][0-9]\b/hover:bg-positive/g'
apply 's/dark:text-green-[0-9][0-9][0-9]\b/dark:text-positive/g'
apply 's/dark:bg-green-[0-9][0-9][0-9]\b/dark:bg-positive/g'
apply 's/\bbg-emerald-[0-9][0-9][0-9]\b/bg-positive/g'
apply 's/\btext-emerald-[0-9][0-9][0-9]\b/text-positive/g'
apply 's/\bborder-emerald-[0-9][0-9][0-9]\b/border-positive/g'
apply 's/hover:bg-emerald-[0-9][0-9][0-9]\b/hover:bg-positive/g'
apply 's/dark:text-emerald-[0-9][0-9][0-9]\b/dark:text-positive/g'
apply 's/dark:bg-emerald-[0-9][0-9][0-9]\b/dark:bg-positive/g'

# ── AMBER + YELLOW + ORANGE → warning ────────────────────────────
apply 's/\bbg-amber-900\b/bg-warning\/10/g'
apply 's/\bbg-amber-50\b/bg-warning\/10/g'
apply 's/\bbg-yellow-900\b/bg-warning\/10/g'
apply 's/\bbg-amber-[0-9][0-9][0-9]\b/bg-warning/g'
apply 's/\btext-amber-[0-9][0-9][0-9]\b/text-warning/g'
apply 's/\bborder-amber-[0-9][0-9][0-9]\b/border-warning/g'
apply 's/dark:text-amber-[0-9][0-9][0-9]\b/dark:text-warning/g'
apply 's/dark:bg-amber-[0-9][0-9][0-9]\b/dark:bg-warning/g'
apply 's/dark:border-amber-[0-9][0-9][0-9]\b/dark:border-warning/g'
apply 's/hover:bg-amber-[0-9][0-9][0-9]\b/hover:bg-warning/g'
apply 's/\bbg-yellow-[0-9][0-9][0-9]\b/bg-warning/g'
apply 's/\btext-yellow-[0-9][0-9][0-9]\b/text-warning/g'
apply 's/\bborder-yellow-[0-9][0-9][0-9]\b/border-warning/g'
apply 's/dark:text-yellow-[0-9][0-9][0-9]\b/dark:text-warning/g'
apply 's/dark:bg-yellow-[0-9][0-9][0-9]\b/dark:bg-warning/g'
apply 's/dark:border-yellow-[0-9][0-9][0-9]\b/dark:border-warning/g'
apply 's/\bbg-orange-[0-9][0-9][0-9]\b/bg-warning/g'
apply 's/\btext-orange-[0-9][0-9][0-9]\b/text-warning/g'
apply 's/dark:text-orange-[0-9][0-9][0-9]\b/dark:text-warning/g'
apply 's/dark:bg-orange-[0-9][0-9][0-9]\b/dark:bg-warning/g'
apply 's/hover:bg-orange-[0-9][0-9][0-9]\b/hover:bg-warning/g'

# ── SKY → info ────────────────────────────────────────────────────
apply 's/\bbg-sky-[0-9][0-9][0-9]\b/bg-info/g'
apply 's/\btext-sky-[0-9][0-9][0-9]\b/text-info/g'
apply 's/dark:text-sky-[0-9][0-9][0-9]\b/dark:text-info/g'
apply 's/dark:bg-sky-[0-9][0-9][0-9]\b/dark:bg-info/g'

# ── PURPLE + VIOLET + INDIGO → accent ────────────────────────────
apply 's/\bbg-purple-[0-9][0-9][0-9]\b/bg-accent/g'
apply 's/\btext-purple-[0-9][0-9][0-9]\b/text-accent/g'
apply 's/dark:text-purple-[0-9][0-9][0-9]\b/dark:text-accent/g'
apply 's/\bbg-violet-[0-9][0-9][0-9]\b/bg-accent/g'
apply 's/\btext-violet-[0-9][0-9][0-9]\b/text-accent/g'
apply 's/dark:text-violet-[0-9][0-9][0-9]\b/dark:text-accent/g'
apply 's/\bbg-indigo-[0-9][0-9][0-9]\b/bg-accent/g'
apply 's/\btext-indigo-[0-9][0-9][0-9]\b/text-accent/g'
apply 's/dark:text-indigo-[0-9][0-9][0-9]\b/dark:text-accent/g'

# ── GRAY / SLATE / ZINC / NEUTRAL → surface tokens ───────────────
# Light text (gray-100/200 in dark contexts) → text
apply 's/\btext-gray-100\b/text-text/g'
apply 's/\btext-gray-200\b/text-text/g'
apply 's/\btext-slate-200\b/text-text/g'
apply 's/dark:text-gray-100\b/dark:text-text/g'
apply 's/dark:text-gray-200\b/dark:text-text/g'

# Mid-gray text → text-secondary
apply 's/\btext-gray-300\b/text-text-secondary/g'
apply 's/\btext-gray-400\b/text-text-secondary/g'
apply 's/\btext-gray-500\b/text-text-secondary/g'
apply 's/\btext-gray-600\b/text-text-secondary/g'
apply 's/\btext-slate-300\b/text-text-secondary/g'
apply 's/\btext-slate-400\b/text-text-secondary/g'
apply 's/\btext-slate-500\b/text-text-secondary/g'
apply 's/\btext-slate-600\b/text-text-secondary/g'
apply 's/dark:text-gray-300\b/dark:text-text-secondary/g'
apply 's/dark:text-gray-400\b/dark:text-text-secondary/g'
apply 's/dark:text-gray-500\b/dark:text-text-secondary/g'
apply 's/dark:text-gray-600\b/dark:text-text-secondary/g'
apply 's/dark:text-slate-300\b/dark:text-text-secondary/g'
apply 's/dark:text-slate-400\b/dark:text-text-secondary/g'
apply 's/dark:text-slate-500\b/dark:text-text-secondary/g'
apply 's/dark:text-slate-600\b/dark:text-text-secondary/g'
apply 's/hover:text-gray-[0-9][0-9][0-9]\b/hover:text-text/g'
apply 's/dark:hover:text-gray-[0-9][0-9][0-9]\b/dark:hover:text-text/g'

# Dark-gray text → text (body copy)
apply 's/\btext-gray-700\b/text-text/g'
apply 's/\btext-gray-800\b/text-text/g'
apply 's/\btext-gray-900\b/text-text/g'
apply 's/\btext-slate-700\b/text-text/g'
apply 's/\btext-slate-800\b/text-text/g'
apply 's/dark:text-gray-700\b/dark:text-text/g'
apply 's/dark:text-gray-800\b/dark:text-text/g'
apply 's/dark:text-gray-900\b/dark:text-text/g'

# bg surfaces
apply 's/\bbg-gray-50\b/bg-bg-subtle/g'
apply 's/\bbg-gray-100\b/bg-bg-subtle/g'
apply 's/\bbg-slate-50\b/bg-bg-subtle/g'
apply 's/\bbg-slate-100\b/bg-bg-subtle/g'
apply 's/\bbg-gray-200\b/bg-active/g'
apply 's/\bbg-slate-200\b/bg-active/g'
apply 's/\bbg-gray-700\b/bg-surface/g'
apply 's/\bbg-gray-800\b/bg-surface/g'
apply 's/\bbg-slate-700\b/bg-surface/g'
apply 's/\bbg-slate-800\b/bg-surface/g'
apply 's/\bbg-gray-900\b/bg-bg/g'
apply 's/\bbg-gray-950\b/bg-bg/g'

apply 's/hover:bg-gray-50\b/hover:bg-bg-subtle/g'
apply 's/hover:bg-gray-100\b/hover:bg-bg-subtle/g'
apply 's/hover:bg-gray-200\b/hover:bg-active/g'
apply 's/hover:bg-gray-700\b/hover:bg-surface/g'
apply 's/hover:bg-gray-800\b/hover:bg-surface/g'
apply 's/dark:bg-gray-50\b/dark:bg-bg-subtle/g'
apply 's/dark:bg-gray-100\b/dark:bg-bg-subtle/g'
apply 's/dark:bg-gray-200\b/dark:bg-active/g'
apply 's/dark:bg-gray-700\b/dark:bg-surface/g'
apply 's/dark:bg-gray-800\b/dark:bg-surface/g'
apply 's/dark:hover:bg-gray-50\b/dark:hover:bg-bg-subtle/g'
apply 's/dark:hover:bg-gray-100\b/dark:hover:bg-bg-subtle/g'
apply 's/dark:hover:bg-gray-200\b/dark:hover:bg-active/g'
apply 's/dark:hover:bg-gray-700\b/dark:hover:bg-surface/g'
apply 's/dark:hover:bg-gray-800\b/dark:hover:bg-surface/g'

apply 's/\bborder-gray-[0-9][0-9][0-9]\b/border-border/g'
apply 's/dark:border-gray-[0-9][0-9][0-9]\b/dark:border-border/g'
apply 's/\bborder-slate-[0-9][0-9][0-9]\b/border-border/g'

echo "Done"
